services:
  nginx:
    image: nginx:latest
    container_name: nginx_turkcell
    volumes:
      - ./html:/usr/share/nginx/html
    networks:
      - x_company
    logging:
      driver: loki
      options:
        loki-url: "http://loki_x-company:3100/loki/api/v1/push"
        loki-retries: 5
        loki-max-backoff: 800ms
        loki-timeout: 5s
        keep-file: "true"
        mode: "non-blocking"
    ports:
      - 8081:80
    restart: unless-stopped

networks:
  x_company:
    external: true
