---
services:
  loki:
    container_name: loki_turkcell
    image: grafana/loki:3.4.1
    command: "-config.file=/etc/loki/config.yaml"
    ports:
      - "3100:3100"
    volumes:
      - ./config/config.yaml:/etc/loki/config.yaml:ro
      - data_loki:/loki:rw
    networks:
      - kudim
    restart: unless-stopped

volumes:
  data_loki:
    external: true

networks:
  kudim:
    external: true
