---
services:
  loki:
    container_name: loki_x-company
    image: grafana/loki:3.4.1
    command: "-config.file=/etc/loki/config.yaml"
    ports:
      - "3100:3100"
    volumes:
      - ./loki/config/config.yaml:/etc/loki/config.yaml:ro
    networks:
      - x_company
    restart: unless-stopped


  grafana:
    image: grafana/grafana-enterprise
    container_name: grafana_x-company
    restart: unless-stopped
    networks:
      - x_company
    ports:
      - "3000:3000"




networks:
  x_company:
    external: true
